# project: enzyme-stability
# name: example_training

datasets: [megascale]

training:
  num_workers: 0
  #learn_rate: 0.001
  epochs: 100 # 100
  lr_schedule: true
  unfreeze_epochs: [0, 10, 20]
  mpnn_learn_rate: 0.001
  use_distogram: False
  # two_stage: true
  encoder_lr_init: 0.0001
  encoder_lr_final: 0.00001
  edge_lr_init: 0.001
  edge_lr_final: 0.0001
  head_lr_init: 0.001
  head_lr_final: 0.0001
  light_attention_lr_init: 0.001
  light_attention_lr_final: 0.0001

model:
  hidden_dims: [64, 32]
  subtract_mut: true
  num_final_layers: 2
  freeze_weights: False
  load_pretrained: true
  lightattn: true
