model:
  L_max: 1024
  depth: 5
  dropout: 0.0
  hidden_channels: 64
  type: EGNN
training:
  batch_size: 512
  data_path: /pasteur/appa/scratch/nportal/boltz/stability_prediction/packed_distance_distogram
  device: cuda
  epochs: 80
  eta_min: 1.0e-06
  focal_loss: false
  initial_lr: 0.0001
  weight_decay: 0.0001
